### ISSUE TITLE
PacketAligner benchmark reports data corruption if the input data comes in chunks of size 128B or 512B

### ISSUE THREAD

**Issue by YoshiWalsh** [YoshiWalsh/mpegts-tools#1]
Running the PacketAligner benchmark with a chunk size of 128 or 512 bytes causes the following error:

```
(node:16404) UnhandledPromiseRejectionWarning: Error: Data stream corrupted
warning.js:25
    at Promise.all.inputAndOutputBuffers.map.io (d:\git\mpegts-tools\benchmarking\PacketAligner.ts:73:11)
    at Array.map (<anonymous>)
    at d:\git\mpegts-tools\benchmarking\PacketAligner.ts:67:42
    at Generator.next (<anonymous>)
    at fulfilled (d:\git\mpegts-tools\dist\benchmarking\PacketAligner.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I'm not sure if this is an issue with the verification algorithm in the benchmark, or if the data is actually being corrupted.

It seems the corruption (or false alarm) happens very early on, as there's no "Alignment skipped 187 bytes" message in console.

I reproduced this both before and after e787dc4bb28315b87695ffe694f45f87b4f3dec6.

### Steps to reproduce:

1. In /benchmarking/PacketAligner.ts, change `segmentBytes` to either 128 or 512
2. Run the benchmark
3. Observe the error message

**Comment by YoshiWalsh** [comment]
The bug I've fixed was caused by e787dc4, so I'm not sure why this bug also occurred before that commit. It must've been a different cause.

EDIT: Ah, I've just realised something else. In the commit description I said I wasn't sure why it only happened when the input chunks were small. I've worked it out, it happened because the chunk size was less than `3 * MPEGTS_PACKET_LENGTH`, which caused the leftovers buffer to contain entire valid chunks due to the sync acquisition having to wait for new data.
